from os import environ

MONGOALCHEMY_DATABASE = environ.get('MONGODB_DATABASE')
MONGOALCHEMY_SERVER = environ.get('MONGODB_HOST')
MONGOALCHEMY_PORT = environ.get('MONGODB_PORT')
MONGOALCHEMY_USER = environ.get('MONGODB_USER')
MONGOALCHEMY_PASSWORD = environ.get('MONGODB_PASSWORD')
MONGOALCHEMY_SERVER_AUTH = False

MEMCACHE_SERVERS = environ.get('MEMCACHE_SERVERS')
MEMCACHE_USERNAME = environ.get('MEMCACHE_USERNAME')
MEMCACHE_PASSWORD = environ.get('MEMCACHE_PASSWORD')

MEMCACHED_HOST = environ.get('MEMCACHED_HOST')
MEMCACHED_PORT = environ.get('MEMCACHED_PORT')

SUNLIGHT_API_KEY = environ.get('SUNLIGHT_API_KEY')

TWILIO_ACCOUNT = environ.get("TWILIO_ACCOUNT_SID")
TWILIO_TOKEN = environ.get("TWILIO_AUTH_TOKEN")
TWILIO_OUTGOING = environ.get("TWILIO_OUTGOING")

PORT = int(environ.get('PORT', 5000))

APP_DEBUG = environ.get("APP_DEBUG", False)

APPLICATION_ROOT = environ.get('APPLICATION_ROOT')

SESSION_SECRET = environ.get('SESSION_SECRET')
